import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import { authOptions } from "@/services/auth/auth";
import { ReactElement } from "react";
import { appNavigation } from "@/utils/constants";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <div className=" max-w-7xl mx-auto h-screen  relative w-full grid grid-cols-4 lg:grid-cols-5">
      <div className="hidden p-6 gap-2 md:flex flex-col">
        {appNavigation.map((item) => <div className=" text-sm flex items-center space-x-3 border px-4 rounded-md py-2.5" key={item.option}><img alt="" className="h-8 w-8" src={item.icon as string} /><p>{item.option}</p></div>)}
        <div className=" bg-[#23fed6] text-sm flex items-center space-x-3 border px-4 rounded-md py-2.5"><img alt="" className="h-12 p-1 bg-white w-12 object-cover rounded-full object-top" src='https://static.zerochan.net/Sage.%28Valorant%29.full.4051819.jpg' /><p className=" font-semibold">Sage</p></div>
        <div className=" bg-gray-100 dark:bg-gray-800 text-sm flex items-center space-x-3 border px-4 rounded-md py-2.5"><img alt="" className="h-8 p-1 bg-white w-8 object-cover rounded-full object-top" src='https://img.icons8.com/color/48/medical-doctor.png' /><p>Therapist</p></div>
        <div className=" bg-gray-100 dark:bg-gray-800 text-sm flex items-center space-x-3 border px-4 rounded-md py-2.5"><img alt="" className="h-8 p-1 bg-white w-8 object-cover rounded-full object-top" src='https://img.icons8.com/color/48/plant-under-sun--v1.png' /><p>Health Coach</p></div>
      </div>
      <div className=" flex-1  col-span-4 md:col-span-3 lg:col-span-4">
        {children}
      </div>
    </div>
  );
}
